apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Kim-Min-Gyeong/21-iceT-gitops-eks
    targetRevision: main
    path: apps/base/spring
  destination:
    server: https://kubernetes.default.svc
    namespace: spring-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
